DELETE http://localhost:1337/api/persons/63363a2c0a51f58bafe047bd

###

POST http://localhost:1337/api/persons
content-type: application/json

{
  "name": "12",
  "phoneNumber": "12312313"
}
###
PUT http://localhost:1337/api/persons/63363a2c0a51f583afe047bd
content-type: application/json

{
  "name": "João Pedro",
  "phoneNumber": ""
}